import axios from "axios";
import dotenv from "dotenv";
import { checkSafety } from "./safety.service.js";
import { embedQuery } from "./embedding.service.js";
import { retrieveTopChunks } from "./retrieve.service.js";
import QueryLog from "../models/Querylogs.js";

dotenv.config();

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const GEMINI_MODEL = "gemini-flash-latest";

export async function askQuestion(query) {
  // 1. Check Safety
  const safety = checkSafety(query);
  if (safety.isUnsafe) {
    // Build safety message with exact wording from assignment + debug info
    const safetyMessage = [
      safety.debugInfo,
      "",
      "Your question touches on an area that can be risky without personalized guidance.",
      "",
      "Instead of headstands, consider gentle supine poses and breathing work.",
      "",
      "Please consult a doctor or certified yoga therapist before attempting these poses."
    ].join("\n");

    const log = await QueryLog.create({
      query,
      answer: safetyMessage,
      isUnsafe: true,
      sources: []
    });

    return {
      answer: safetyMessage,
      sources: [],
      isUnsafe: true,
      queryLogId: log._id
    };
  }

  try {
    const queryEmbedding = await embedQuery(query);
    const topChunks = retrieveTopChunks(queryEmbedding, 3);
    const context = topChunks.map(c => c.text).join("\n\n");
    const sources = [...new Set(topChunks.map(c => c.source))];

    const prompt = `
You are a Yoga and Wellness Assistant using Retrieval-Augmented Generation.

Use the provided context to answer the user's question.

Guidelines:
- Reason semantically, not just by exact keywords
- Treat synonyms and related concepts as equivalent when meaning matches
- Combine information from multiple context chunks if needed
- If information is partially available, summarize what is known and state limitations
- Do not hallucinate or provide medical diagnoses
- Respect all safety and contraindication information

Context:
${context}

User Question:
${query}

Answer:
    `;

    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`,
      {
        contents: [
          {
            parts: [{ text: prompt }]
          }
        ]
      },
      {
        params: { key: GEMINI_API_KEY }
      }
    );

    if (!response.data.candidates?.length) {
      throw new Error("No response generated by Gemini");
    }

    const answer = response.data.candidates[0].content.parts[0].text;

    //saving to mongodb
    const log = await QueryLog.create({
      query,
      answer,
      isUnsafe: false,
      sources: sources
    });

    return {
      answer,
      sources,
      isUnsafe: false,
      queryLogId: log._id
    };
  } catch (error) {
    console.error("DEBUG ERROR:", error.response?.data || error.message);
    throw new Error("Failed to process your yoga query. Please try again later.");
  }
}
