import axios from "axios";
import dotenv from "dotenv";
import { checkSafety } from "./safety.service.js";
import { embedQuery } from "./embedding.service.js";
import { retrieveTopChunks } from "./retrieve.service.js";
import QueryLog from "../models/Querylogs.js";

dotenv.config();

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const GEMINI_MODEL = "gemini-flash-latest";

export async function askQuestion(query) {
  // 1. Check Safety
  const safety = checkSafety(query);
  if (safety.isUnsafe) {
    const safetyAnswer = `This query involves a health condition or sensitive topic (${safety.reason}). Please consult a qualified doctor or yoga instructor before proceeding.`;

    const log = await QueryLog.create({
      query,
      answer: safetyAnswer,
      isUnsafe: true,
      sources: []
    });

    return {
      answer: safetyAnswer,
      sources: [],
      isUnsafe: true,
      queryLogId: log._id
    };
  }

  try {
    const queryEmbedding = await embedQuery(query);
    const topChunks = retrieveTopChunks(queryEmbedding, 3);
    const context = topChunks.map(c => c.text).join("\n\n");
    const sources = [...new Set(topChunks.map(c => c.source))];

    const prompt = `
      You are a specialized Yoga Assistant. Use the following context to answer the user's question accurately.
      If the answer is not in the context, say that you don't have enough information but provide general yoga safety tips.
      
      Context:
      ${context}
      
      User Question: ${query}
      
      Answer (be helpful, concise, and professional):
    `;

    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`,
      {
        contents: [
          {
            parts: [{ text: prompt }]
          }
        ]
      },
      {
        params: { key: GEMINI_API_KEY }
      }
    );

    if (!response.data.candidates?.length) {
      throw new Error("No response generated by Gemini");
    }

    const answer = response.data.candidates[0].content.parts[0].text;

    //saving to mongodb
    const log = await QueryLog.create({
      query,
      answer,
      isUnsafe: false,
      sources: sources
    });

    return {
      answer,
      sources,
      isUnsafe: false,
      queryLogId: log._id
    };
  } catch (error) {
    throw new Error("Failed to process your yoga query. Please try again later.");
  }
}
